### PR TITLE
Add bash run.sh script for Mac and Linux.

### PR DESCRIPTION
**Pull request by spyrosoft**

### CODE REVIEW

**Comment by gotyaoi** [comment]
Just a thought, the existence of the python3 command is not necessarily evidence of python >= 3.4. I might opt for just running python3, or python in that order of preference, and then checking version in menu.py.

**Comment by spyrosoft** [comment]
Agreed. Let's do it that way.

**Comment by spyrosoft** [comment]
How's that?

**Comment by gotyaoi** [comment]
Ah, now it lost the check for python3 I think.

And don't worry about rebasing or merging this time, github will automatically merge when I accept the PR.

**Comment by gotyaoi** [comment]
I merged this in #6.

**Pull request closed without merging**
